apiVersion: apps/v1
kind: Deployment
metadata:
  name: postit-export-deployment
spec:
  selector:
    matchLabels:
      app: postit-export
  replicas: 1
  template:
    metadata:
      labels:
        app: postit-export
    spec:
      containers:
        - name: postit-export
          image: rafaelgiro/postit-export
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_HOST
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_USER
              valueFrom: 
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password